services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      retries: 5

  app:
    build:
      context: ./app
    environment:
      DATABASE_URL: postgres://postgres@db:5432/postgres?sslmode=disable
      PORT: 8080
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"