FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# add app
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/server ./cmd/api

# add migration tool
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/migrate ./cmd/migrate

# add migrations
RUN mkdir -p /out/migrations && cp -R ./migrations /out/

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /out/server /app/server
COPY --from=build /out/migrate /app/migrate
COPY --from=build /out/migrations /app/migrations
EXPOSE 8080
CMD ["/app/server"]