apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: invalid:to-be-overwritten
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: app-secrets
        resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"