apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: simple-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: invalid:to-be-overwritten
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: app-secrets
        resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--port=5432"
          - "--address=0.0.0.0"
          - "$(INSTANCE_CONNECTION_NAME)"
        env:
          - name: INSTANCE_CONNECTION_NAME
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: INSTANCE_CONNECTION_NAME
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/credentials.json
        volumeMounts:
          - name: cloudsql-sa
            mountPath: /secrets
            readOnly: true
        ports:
          - containerPort: 5432
      volumes:
        - name: cloudsql-sa
          secret:
            secretName: cloud-sql-credentials