name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        required: true
        options: [staging, prod]
        default: staging
      image_tag:
        description: "Image tag to deploy (default: latest SHA on main)"
        required: false

permissions:
  contents: read
  id-token: write

concurrency:
  group: deploy-${{ inputs.environment }}
  cancel-in-progress: true

env:
  REGION:        ${{ vars.GCP_REGION }}
  PROJECT_ID:    ${{ vars.GCP_PROJECT_ID }}
  CLUSTER:       ${{ vars.GKE_CLUSTER_NAME }}
  NAMESPACE:     simple-web
  IMAGE_REPO:    ${{ vars.IMAGE_REPO }}
  IMAGE_NAME:    ${{ vars.IMAGE_NAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      IMAGE_TAG: ${{ inputs.image_tag != '' && inputs.image_tag || github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Set IMAGE env
        run: echo "IMAGE=${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}" >> "$GITHUB_ENV"

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'kubectl,gke-gcloud-auth-plugin'

      - name: Verify plugin is installed
        run: |
          which kubectl
          which gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials "$CLUSTER" --region "$REGION" --project "$PROJECT_ID"

      - name: Apply base K8s
        run: |
          kubectl apply -f k8s/app/service.yml
          kubectl apply -f k8s/app/deployment.yml

      - name: Sync Secret (DATABASE_URL from environment secrets)
        env:
          DATABASE_PASSWORD: ${{ secrets.PROD_DATABASE_PASSWORD }}
          INSTANCE_CONNECTION_NAME: ${{ vars.INSTANCE_CONNECTION_NAME }}
        run: |
          kubectl -n "$NAMESPACE" create secret generic app-secrets \
            --from-literal=DATABASE_URL="postgres://appuser:${DATABASE_PASSWORD}@127.0.0.1:5432/appdb?sslmode=disable" \
            --from-literal=INSTANCE_CONNECTION_NAME="${INSTANCE_CONNECTION_NAME}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Sync Cloud SQL credentials
        env:
          GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
        run: |
          printf '%s' "$GCP_CREDENTIALS_JSON" > sa.json
          kubectl -n "$NAMESPACE" create secret generic cloud-sql-credentials \
            --from-file=credentials.json=sa.json \
            --dry-run=client -o yaml | kubectl apply -f -
          rm -f sa.json

      - name: Set image & rollout
        run: |
          kubectl -n "$NAMESPACE" set image deploy/app app="$IMAGE"
          kubectl -n "$NAMESPACE" rollout status deploy/app --timeout=180s