name: CI
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: app } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version-file: app/go.mod, cache: true }
      - run: go vet ./...
      - run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - uses: actions/upload-artifact@v4
        if: always()
        with: { name: coverage, path: app/coverage.out }